### ISSUE TITLE
Project Perspectives - System and User Interfaces

### ISSUE THREAD

**Issue by saranya-shanmugam** [antishake/antishake_lib#13]
Write about System and User interfaces in the proposal document

**Comment by saranya-shanmugam** [comment]
Moved to Docs Backlog

**Comment by ruraj** [comment]
Include a little detail about when the scene will be stabilized and when not. In case of UI, basic video controls will also be included like play/pause/next/previous and such.

**Comment by Abdullahejaz** [comment]
I have updated the description column of both the text reader system and the video player system. Just have a look at them once and let me know If there is any changes to make.

And check under the User Interface heading also. I have made some changes there also.

**Comment by saranya-shanmugam** [comment]
Reviewed. Moving to done.
