### ISSUE TITLE
Risks - Consequences

### ISSUE THREAD

**Issue by saranya-shanmugam** [antishake/antishake_lib#24]

**Comment by ruraj** [comment]
"Inconsistent experiences across devices" may not be related to any of the risks listed. We are also assuming that the user is an Android user at the moment.

**Comment by saranya-shanmugam** [comment]
The cause of the risk 'Incompatible operating system platform' could be 'Inconsistent experiences across devices'. As we are aiming to develop a scalable software, thought it would be meaningful to consider other operating platform as well.
