### ISSUE TITLE
Measures of success

### ISSUE THREAD

**Issue by Abdullahejaz** [antishake/antishake_lib#27]
This section of the project proposal will describe about the measures of success of the application.

**Comment by ruraj** [comment]
Should the testing mechanism we discussed (with camera) be included?

**Comment by Abdullahejaz** [comment]
Yes, we can add that point. But right now I am not sure about the effectiveness of that testing mechanism. So I am leaving that for now. In the next project meeting we will discuss about it thoroughly and then if we find it effective, we will add that point also to the measures of success.

**Comment by saranya-shanmugam** [comment]
'After that only we will jump on the next iteration' -  I am removing the line from the proposal as we will not stop the next iteration to test and fix the previous iteration. We will do it in parallel.

**Comment by saranya-shanmugam** [comment]
I guess, we need to quantitatively define the success measures or usability study with effectiveness question.

**Comment by saranya-shanmugam** [comment]
Reviewed. Moving to Done.
