### ISSUE TITLE
As a developer, get familiar with Tools like Git, GitHub, ZenHub, Android Studio (IntelliJ), emulators

### ISSUE THREAD

**Issue by ruraj** [antishake/antishake_lib#3]
Git, GitHub, ZenHub, Android Studio (IntelliJ), emulators

**Comment by saranya-shanmugam** [comment]
We have integrated ZenHub with GitHub, using ZenHub kanban board to track the issues in GitHub. Also, connecting to Git repo and able to take update, commit, push and other activities. Set up Android Studio(IntelliJ) and worked some examples with emulators. Moving to Review.

**Comment by saranya-shanmugam** [comment]
Reviewed, moving to Done.
