### ISSUE TITLE
As a quality measure, we need to integrate TravisCI with GitHub for antishake_lib and antishake_android

### ISSUE THREAD

**Issue by ruraj** [antishake/antishake_lib#4]
This will be done in the second week. Any takers?

**Comment by saranya-shanmugam** [comment]
I can take it so that I will also learn about GitHub and TravisCI

**Comment by saranya-shanmugam** [comment]
I can take it so that I will also learn about GitHub and TravisCI

**Comment by ruraj** [comment]
Are you sure about closing it right now?

**Comment by saranya-shanmugam** [comment]
Sorry, I closed the issue by mistake. Reopened it.

**Comment by Abdullahejaz** [comment]
Assign me also..

**Comment by ruraj** [comment]
I think it looks functional for now. Closing. We can re-open this issue if we need to add any build configuration later.
