### ISSUE TITLE
As a developer, I need to implement detection of shaking

### ISSUE THREAD

**Issue by saranya-shanmugam** [antishake/antishake_lib#41]

**Comment by saranya-shanmugam** [comment]
Hi, I reviewed your commit with isShaking() method and below are some comments. Please review.
1. As you have created dummy values for now, please add comments above those statements. (lines 59-62)
2. Please do not create variables inside the loop. Create outside of the loop and change values inside the loop if needed. (line 65-67)
3. The logic should take the latest 90 values of the input. Here, the code starts with 0 and moves onto 199, 198 and so on. Please create an index assuming that is the latest read pointer of the circular buffer and change code accordingly.
4. The code always says "Shake Detected" for every input value above threshold. I guess, it has to accumulate and find the average and then check with the threshold to confirm shaking detection.

**Comment by Abdullahejaz** [comment]
Okay. I will make the corrections as needed. Thank you for reviewing.
