### ISSUE TITLE
As a developer, I need to integrate and test library interfaces

### ISSUE THREAD

**Issue by saranya-shanmugam** [antishake/antishake_lib#43]

**Comment by saranya-shanmugam** [comment]
I am doing integration part of this task and so assigning it to myself.
Even though we also have the test cases to test each of the functionality, we need to test the complete library interface. Once we have the android application in place, we can do it from there. At that point, any one who does the testing can add into assignees.

**Comment by ruraj** [comment]
I will try to test the entire library with a large test input and check if states are accurately represented. Tested parameters:
Shake detection
Transformation vectors - initially, test in a primitive way by comparing input and output graphs

**Comment by saranya-shanmugam** [comment]
Integration part is completed and created a pull request.
