### ISSUE TITLE
Change library implementation to work in background thread (currently no point of having callback functions)

### ISSUE THREAD

**Issue by ruraj** [antishake/antishake_lib#68]

**Comment by ruraj** [comment]
This is perhaps also causing the delay in output

**Comment by saranya-shanmugam** [comment]
So, a background service requests library for transformation vector and updates the vectors that android app is currently using to screen adjustment.  Android app and the service will run in their own thread. Am I understanding it correct?

**Comment by ruraj** [comment]
I am actually making the library itself work in the background. The application does not need to worry about creating a service specifically to make the library run in the background. Android still needs the service implementation- that's for broadcasting vectors to different activities.

**Comment by saranya-shanmugam** [comment]
I wonder how library can run in background independently, as it has to be invoked by some other thread to get the results. Lets discuss in the meeting.
